#!/usr/bin/env python3
"""Deterministic lint gate for crew work orders.

Scans a rendered .docx (or a markdown/text draft) for the hard-rule leaks that
make a crew doc un-shippable, plus softer patterns worth a human look.

    python3 scripts/wo_lint.py "output/Work Order - HVAC - Alder - 2026-07-29.docx"

Verdicts:
    FAIL    hard-rule leak — fix and regenerate, never hand-deliver
            (prices on a crew doc · unresolved placeholders · AI attribution)
    REVIEW  human look before dispatch
            (options language · negative instructions · ventilation-ratio drift)
    PASS    clean

Exit code 1 on FAIL, else 0 — safe to wire into CI or a pre-dispatch script.
"""

import argparse
import os
import re
import sys

FAIL_CHECKS = [
    ('price_on_crew_doc',
     re.compile(r'\$\s?\d[\d,]*(?:\.\d+)?'),
     'dollar amount on a crew-facing doc — pricing lives in the estimate, never here'),
    ('ai_attribution',
     re.compile(r'\b(claude|chatgpt|gpt-\d|copilot|anthropic|openai|'
                r'generated by ai|ai-generated|an ai assistant)\b', re.I),
     'AI attribution — crew docs are credited to a person'),
    ('unresolved_placeholder',
     re.compile(r'\b(TBD|TODO|FIXME)\b|\{[^}\n]{1,40}\}|<[A-Za-z_ ]{1,30}>|\bX{3,}\b'),
     'unresolved placeholder — crews act on what the doc says; fill it in or cut it'),
]

REVIEW_CHECKS = [
    ('options_language',
     re.compile(r'\b(option [ab12]|either\b.{0,40}\bor\b|alternatively|'
                r"choose between|crew'?s choice)\b", re.I),
     'options language — state what IS happening; decisions are made before dispatch'),
    ('negative_instruction',
     re.compile(r"\b(do not|don'?t|never)\b", re.I),
     'negative instruction — rewrite as the positive action the crew should take'),
]

_RATIO_RE = re.compile(r'\b1\s*[:/]\s*(\d{2,4})\b')


def extract_text(path):
    if path.lower().endswith('.docx'):
        from docx import Document
        doc = Document(path)
        chunks = [p.text for p in doc.paragraphs]
        for table in doc.tables:
            for row in table.rows:
                for cell in row.cells:
                    chunks.append(cell.text)
        return '\n'.join(chunks)
    with open(path, encoding='utf-8') as f:
        return f.read()


def _snippet(text, start, width=60):
    s = max(0, start - width // 2)
    return ' '.join(text[s:s + width].split())


def lint(text, vent_ratio=''):
    findings = []
    for tier, checks in (('FAIL', FAIL_CHECKS), ('REVIEW', REVIEW_CHECKS)):
        for name, rx, why in checks:
            for m in rx.finditer(text):
                findings.append((tier, name, _snippet(text, m.start()), why))
    if vent_ratio:
        for m in _RATIO_RE.finditer(text):
            if m.group(1) != vent_ratio:
                findings.append(('REVIEW', 'vent_ratio_drift', _snippet(text, m.start()),
                                 f'doc says 1:{m.group(1)} but the company standard is '
                                 f'1:{vent_ratio} — confirm local code before dispatch'))
    return findings


def main():
    ap = argparse.ArgumentParser(description='Lint a crew work order for hard-rule leaks.')
    ap.add_argument('path', help='.docx, .md, or .txt to lint')
    ap.add_argument('--config', help='company.md (enables the ventilation-ratio check)')
    ap.add_argument('--quiet', action='store_true', help='verdict line only')
    args = ap.parse_args()

    vent_ratio = ''
    if args.config and os.path.exists(args.config):
        sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
        from brand import load_config
        vent_ratio = load_config(args.config).get('vent_ratio', '')

    findings = lint(extract_text(args.path), vent_ratio)
    fails = [f for f in findings if f[0] == 'FAIL']
    verdict = 'FAIL' if fails else ('REVIEW' if findings else 'PASS')
    counts = f'{len(fails)} hard-rule leak(s), {len(findings) - len(fails)} review item(s)'
    print(f'{verdict} — {counts}')
    if not args.quiet:
        for tier, name, snip, why in findings:
            print(f'  [{tier}] {name}: "…{snip}…"')
            print(f'         {why}')
    sys.exit(1 if fails else 0)


if __name__ == '__main__':
    main()
